/** 64 种人格：严格按文档 V3 表格录入（含表内重复命名） */
export const PERSONA_BY_BITS: Record<string, { letterCode: string; name: string; tagline: string }> = {
  "111111": { letterCode: "ASO GRL", name: "定海神针", tagline: "稳如老狗那个老狗都羡慕你。有主见、有安全感、敢真实、能落地、重细节、讲逻辑——六边形战士本兵。" },
  "111110": { letterCode: "ASO GRH", name: "暖心磐石", tagline: "什么都强就是决策偏感性，你是那种既讲道理又讲人情的最佳搭档。" },
  "111101": { letterCode: "ASO GVL", name: "数据禅师", tagline: "几乎完美只是偶尔被脑洞带飞，务实、稳重、理性——你是团队里最值得信赖的那块基石。" },
  "111011": { letterCode: "ASO PRL", name: "理想灯塔", tagline: "什么都好就是行动力偏弱，你是有远见有温度的灯塔，但记住灯塔也得有人去点灯。" },
  "110111": { letterCode: "ASW GRL", name: "铠甲暖男", tagline: "外在温暖坚定但内心有一层铠甲，你给所有人撑伞却忘了自己也会淋雨。" },
  "101111": { letterCode: "ANO GRL", name: "孤狼领主", tagline: "什么都强就是不太信人，你是那种独自也能把事办漂亮的硬核独行侠。" },
  "011111": { letterCode: "FSO GRL", name: "磐石行者", tagline: "少了点主见但其余全满，你是最可靠的执行者——别人指方向你就能跑通全场。" },
  "111100": { letterCode: "ASO GRV", name: "感性磐石", tagline: "什么都好就是决策偏感性，你的温暖是礼物但也偶尔让逻辑让了路。" },
  "111010": { letterCode: "ASO PRL", name: "灯塔·行动版", tagline: "几乎完美只是被概念直觉拉偏了务实感，你是那种想法很美但落地要补课的人。" },
  "111001": { letterCode: "ASO PVL", name: "理想·务实版", tagline: "有主见有安全感敢展露，但行动力和信息加工待提升——别想了，先做起来。" },
  "110110": { letterCode: "ASW GRH", name: "铠甲暖男", tagline: "有主见有安全感但情感隔离——你需要学会偶尔卸下铠甲让人看到真实的你。" },
  "110101": { letterCode: "ASW GVL", name: "铠甲数据师", tagline: "稳健、务实、理性但情感有壁——你的铠甲保护了你，也隔离了温度。" },
  "110011": { letterCode: "ASW PRL", name: "理想暖铠甲", tagline: "有主见有安全感但行动力弱且情绪有隔离，你是那种想法很多但做不动的纠结型。" },
  "101110": { letterCode: "ANO GRH", name: "暖逻辑独行侠", tagline: "独立、开放、务实又温暖，唯一缺的是关系中的安全感——试着相信有人值得你靠近。" },
  "101101": { letterCode: "ANO PVL", name: "理性独行侠", tagline: "有主见、敢展露、能落地、讲逻辑，但亲密关系中的不安全感是你最大的软肋。" },
  "101011": { letterCode: "ANW GRL", name: "孤狼实干家", tagline: "独立、能干、理性，但不太敢信任别人也不太敢展露脆弱——铠甲下你也值得被温柔对待。" },
  "100111": { letterCode: "ASNPRL", name: "安全港·理想版", tagline: "你有主见有安全感敢展露，但行动力和信息加工偶尔掉链子——你值得更好的执行力。" },
  "011110": { letterCode: "FSO GRH", name: "暖心执行者", tagline: "干活利索又照顾人感受，只是在自我定位和关系安全感上还需要更多笃定。" },
  "011101": { letterCode: "FSO PVL", name: "务实舵手", tagline: "脚踏实地、逻辑在线，但主见和安全感的不足让你偶尔成为别人方向的执行者。" },
  "011011": { letterCode: "FSW GRL", name: "实干铠甲", tagline: "能干但不爱展露情绪，你是那种活干完了人没声响的类型，偶尔也该让人看见你的累。" },
  "010111": { letterCode: "FNO GRL", name: "沉默磐石", tagline: "话不多但句句到位，你把行动力和逻辑藏在沉默背后，只是不太敢求助。" },
  "001111": { letterCode: "FSO GRL", name: "双面特工", tagline: "外表随和内心有主，你用开放和务实掩盖了不为人知的焦虑。" },
  "111000": { letterCode: "ASO GRH", name: "感性暖磐石·理想版", tagline: "有主见有安全感敢展露但行动信息决策偏低——你的想法很好但需要更强的执行落地。" },
  "110100": { letterCode: "ASW GRH", name: "铠甲暖男·理想版", tagline: "有主见有安全感能落地够温暖但情感隔离——试着让人看到铠甲下面的你。" },
  "110010": { letterCode: "ASW PVL", name: "数据暖铠甲", tagline: "有主见有安全感务实理性但行动情感偏低——你是个好分析师但不是好的行动者。" },
  "110001": { letterCode: "ASW PRL", name: "理想暖铠甲", tagline: "有主见有安全感但行动信息情感都偏低——你的舒适区很安全但也很小。" },
  "101100": { letterCode: "ANO GRH", name: "暖独行侠", tagline: "有主见敢展露能落地够温暖，但安全感和情感隔离——你的铠甲让你强大也让你孤独。" },
  "101010": { letterCode: "ANW GVL", name: "孤狼数据师", tagline: "有主见敢展露能落地讲逻辑但安全感和情感开放不足——信任一个人试试看？" },
  "101001": { letterCode: "ANO PRL", name: "理性独行侠·理想版", tagline: "有主见敢展露讲逻辑但安全感行动力信息加工不足——你的独立性是铠甲也是牢笼。" },
  "100110": { letterCode: "ASN GRH", name: "暖理想港", tagline: "有主见有安全感能落地够温暖，但情感封闭和信息加工偏概念——偶尔展露脆弱会让你更完整。" },
  "100101": { letterCode: "ASN PVL", name: "理想务实版", tagline: "有主见有安全感能落地讲逻辑，但情感隔离和信息加工偏概念——你值得更丰富的情感生活。" },
  "100011": { letterCode: "ASNPRL", name: "理想型安全港", tagline: "有主见有安全感但其余四项偏低——你是有想法的人，但行动力和信息加工需要跟上。" },
  "011100": { letterCode: "FSO GRH", name: "暖心执行者", tagline: "行动力在线又温暖，但主见、安全感和情感开放度不足让你容易被忽视感受。" },
  "011010": { letterCode: "FSW GRL", name: "实干铠甲·理性版", tagline: "理性、务实、能干，但情感隔离、方向感和安全感不足——铠甲是保护也是监狱。" },
  "011001": { letterCode: "FSW PVL", name: "理想实干铠甲", tagline: "有行动力和务实感但方向迷茫、情感封闭、安全感缺失——你需要一个信任的人帮你校准方向。" },
  "010110": { letterCode: "FNO GRH", name: "暖执行·沉默版", tagline: "干活温暖又靠谱，只是不爱展露且主见不足——试着发一次声，你会发现世界愿意听。" },
  "010101": { letterCode: "FNO PVL", name: "数据沉默者", tagline: "务实、理性、不爱展露，但主见和安全感的不足让你成为工具人而非决策者。" },
  "010011": { letterCode: "FNW GRL", name: "沉默实干派", tagline: "不爱展露情绪但干活扎实讲逻辑，主见和安全感的缺失让你跟随性很强。" },
  "001110": { letterCode: "FSO GRH", name: "暖心实干者", tagline: "干活利索又温暖，但缺乏主见和安全感让你成为最好用的人而非最自由的人。" },
  "001101": { letterCode: "FSO PVL", name: "务实数据师", tagline: "细节和逻辑在线，但自我定位、安全感和情感开放度都需要补课。" },
  "001011": { letterCode: "FSW GRL", name: "实干沉默者", tagline: "埋头干活不多话，但方向感和安全感不足让你像没有锚的船。" },
  "000111": { letterCode: "FSN GRL", name: "执行·随波版", tagline: "没有主见和安全感的加持，你靠行动力和理性干活，但方向感需要别人定。" },
  "110000": { letterCode: "ASW GRH", name: "铠甲暖磐石·理想版", tagline: "有主见有安全感但行动信息决策情感全低——你的舒适区很安全但世界很大。" },
  "101000": { letterCode: "ANO GRH", name: "独立感性者", tagline: "有主见和敢展露但其余全低——你很真实但方向感行动力和决策力都需要补课。" },
  "100100": { letterCode: "ANO GRH", name: "暖独行·理想版", tagline: "有主见和温暖但行动和情感不足——你有人见人爱的一面但内里空空。" },
  "100010": { letterCode: "ASW PVL", name: "理性铠甲·理想版", tagline: "有主见和理性但情感行动全低——你是个冷的理想主义者，需要更多温度和行动。" },
  "100001": { letterCode: "ASN PRL", name: "理想独行·安全版", tagline: "有主见和理想但其余不足——你的想法很美但行动力和情感连接都跟不上。" },
  "011000": { letterCode: "FSW GRL", name: "铠甲实干者·理性版", tagline: "有安全感行动力理性但其余不足——你干活靠谱但不展露情感，让人捉摸不透。" },
  "010100": { letterCode: "FNO GRH", name: "暖心沉默者", tagline: "有安全感能干活够温暖但主见不足情感封闭——你是一块安静的暖石。" },
  "010010": { letterCode: "FNO PVL", name: "理性沉默·安全版", tagline: "有安全感务实理性但其余不足——你是个靠谱的分析者但不够主动也不够展露。" },
  "010001": { letterCode: "FNW PRL", name: "沉默理想派", tagline: "只有安全和理想，其余全低——你想得美但做不动，还不愿让人看到真实的你。" },
  "001100": { letterCode: "FSO GRH", name: "暖心实干者·沉默版", tagline: "只会行动和共情，但主见安全感和情感开放不足——你是那个干活最多但最少被看见的人。" },
  "001010": { letterCode: "FSW GVL", name: "铠甲数据师·沉默版", tagline: "只会务实和理性，但情感封闭且方向安全行动不足——你的分析很强但缺乏温度和方向。" },
  "001001": { letterCode: "FSW PRL", name: "沉默理想实干者", tagline: "只会行动和逻辑但情感封闭、主见缺失、安全感低——你像一台沉默运转的机器。" },
  "000110": { letterCode: "FSN GRH", name: "随波暖心人", tagline: "只会干活和共情，其余全低——你是个好同事但不是自己的主人。" },
  "000101": { letterCode: "FSN GVL", name: "随波数据师", tagline: "只会务实和理性，其余全低——你是团队里的工具人，该想想自己到底要什么了。" },
  "000011": { letterCode: "FSN PRL", name: "随波实干者", tagline: "只会埋头干活讲逻辑，其余维度全低——你是流水线上最勤奋也最没有自主权的那个人。" },
  "100000": { letterCode: "ASNPRL", name: "理想独行侠·全面瘫版", tagline: "只有主见——你很笃定自己要走哪条路，但走不动、不信人、不展露、不落地。" },
  "010000": { letterCode: "FNO GRL", name: "沉默安全者", tagline: "只有安全感——你在关系中是放松的，但生活其他方面全面失守。" },
  "001000": { letterCode: "FSW GRL", name: "实干沉默者·铠甲版", tagline: "只有行动力——你埋头干活但不知道为了什么，也不让人看到你的累。" },
  "000100": { letterCode: "FSN GRH", name: "暖心随波者", tagline: "只有共情在线——你是那种永远在照顾别人感受但自己没有方向的人。" },
  "000010": { letterCode: "FSN PRL", name: "遐想随波者", tagline: "六维里只有概念直觉——你的脑洞很美但其余全瘫，属于想得很远做得很少的典型。" },
  "000001": { letterCode: "FSN PVL", name: "数据随波者", tagline: "六维里只有逻辑在线——你是那个永远在算账但不知道自己在算什么的人。" },
  "000000": { letterCode: "FNPW VH", name: "浮萍仙子", tagline: "六维全低：没主见、怕被抛弃、情感封闭、想太多做不动、爱脑洞、决策全凭感觉——你像一片没有根的浮萍，被每一阵风吹着走。好消息是：从任何一个维度开始改变，都是向上。" },
};

export function getPersona(bits: string) {
  return (
    PERSONA_BY_BITS[bits] ?? {
      letterCode: bits,
      name: "未命名旅人",
      tagline: "你的六维编码尚未收录，但每一次选择都在勾勒你自己。",
    }
  );
}
