import type { SixDimQuestion } from "./meta";

export const SIX_DIM_QUESTIONS: SixDimQuestion[] = [
  {
    id: "q1",
    index: 1,
    dim: "agency",
    kind: "scenario",
    text: "你做了份旅行攻略发群里，有人说「现在谁还做攻略啊」：",
    options: [
      { key: "A", text: "坚持分享——攻略党永不认输", score: 5 },
      { key: "B", text: "不争，但心里觉得自己没毛病", score: 4 },
      { key: "C", text: "有点动摇，要不折中一下", score: 3 },
      { key: "D", text: "开始怀疑自己是不是太死板了", score: 2 },
      { key: "E", text: "默默撤回，确实没必要", score: 1 },
    ],
  },
  {
    id: "q2",
    index: 2,
    dim: "agency",
    kind: "scenario",
    text: "群里讨论一个话题，大家观点一致，你有不同看法：",
    options: [
      { key: "A", text: "直接说，不怕不一样", score: 5 },
      { key: "B", text: "会说，但不坚持", score: 4 },
      { key: "C", text: "纠结一下，看气氛", score: 3 },
      { key: "D", text: "基本不说，怕不合群", score: 2 },
      { key: "E", text: "跟着大家走", score: 1 },
    ],
  },
  {
    id: "q3",
    index: 3,
    dim: "attachment",
    kind: "scenario",
    text: "发了条走心消息，对方已读不回大半天：",
    options: [
      { key: "A", text: "没事，对方在忙", score: 5 },
      { key: "B", text: "偶尔想起，但不影响做事", score: 4 },
      { key: "C", text: "有点在意，会看手机", score: 3 },
      { key: "D", text: "开始想自己是不是说错了", score: 2 },
      { key: "E", text: "忍不住再发一条追问", score: 1 },
    ],
  },
  {
    id: "q4",
    index: 4,
    dim: "attachment",
    kind: "scenario",
    text: "好朋友有了新朋友，周末不再第一时间叫你：",
    options: [
      { key: "A", text: "正常，我也有我的安排", score: 5 },
      { key: "B", text: "偶尔会想，但理解支持", score: 4 },
      { key: "C", text: "有点失落，但不会表现", score: 3 },
      { key: "D", text: "担心关系在变淡", score: 2 },
      { key: "E", text: "焦虑，想找对方确认", score: 1 },
    ],
  },
  {
    id: "q5",
    index: 5,
    dim: "defense",
    kind: "scenario",
    text: "工作出了个小差错被领导当面指出：",
    options: [
      { key: "A", text: "大方承认，跟同事讨论补救", score: 5 },
      { key: "B", text: "承认，有点尴尬但很快调整", score: 4 },
      { key: "C", text: "嘴上说改，内心疯狂自我检讨", score: 3 },
      { key: "D", text: "表面淡定，内心已想了十遍", score: 2 },
      { key: "E", text: "恨不得当场消失", score: 1 },
    ],
  },
  {
    id: "q6",
    index: 6,
    dim: "defense",
    kind: "scenario",
    text: "身体不太舒服，连续几天状态差：",
    options: [
      { key: "A", text: "直接说「我最近状态不好」", score: 5 },
      { key: "B", text: "聊天时自然提起，不藏", score: 4 },
      { key: "C", text: "想说但怕传递负能量", score: 3 },
      { key: "D", text: "问起就说「还行」", score: 2 },
      { key: "E", text: "谁问都说「挺好的」", score: 1 },
    ],
  },
  {
    id: "q7",
    index: 7,
    dim: "action",
    kind: "scenario",
    text: "立了 flag——两周学会三道菜，第一天你会：",
    options: [
      { key: "A", text: "搜菜谱买食材，今晚就开火", score: 5 },
      { key: "B", text: "看看教程，明天采购", score: 4 },
      { key: "C", text: "收藏一堆视频，周末再说", score: 3 },
      { key: "D", text: "觉得麻烦，一直没动", score: 2 },
      { key: "E", text: "刷了半小时视频，点了外卖", score: 1 },
    ],
  },
  {
    id: "q8",
    index: 8,
    dim: "processing",
    kind: "scenario",
    text: "朋友推荐一部电影说「主题深刻、隐喻丰富」：",
    options: [
      { key: "A", text: "先问「讲的什么？好看吗？」", score: 5 },
      { key: "B", text: "会看，但更关注剧情角色", score: 4 },
      { key: "C", text: "都行，看心情", score: 3 },
      { key: "D", text: "被「隐喻丰富」吸引了", score: 2 },
      { key: "E", text: "就爱这种需要解读的作品", score: 1 },
    ],
  },
  {
    id: "q9",
    index: 9,
    dim: "decision",
    kind: "scenario",
    text: "两个好朋友闹矛盾，都来找你吐槽：",
    options: [
      { key: "A", text: "帮双方分析对错，掰开讲清楚", score: 5 },
      { key: "B", text: "讲事实逻辑，但照顾面子", score: 4 },
      { key: "C", text: "两边都听，当和事佬", score: 3 },
      { key: "D", text: "先安抚情绪，道理以后说", score: 2 },
      { key: "E", text: "谁更受伤就站谁那边", score: 1 },
    ],
  },
  {
    id: "q10",
    index: 10,
    dim: "agency",
    kind: "likert",
    text: "我对自己的评价不太会因为别人的一句话就大起大落。",
  },
  {
    id: "q11",
    index: 11,
    dim: "agency",
    kind: "likert",
    reverse: true,
    text: "做重要决定时，我总会反复想「别人会怎么看我这个选择」。",
  },
  {
    id: "q12",
    index: 12,
    dim: "attachment",
    kind: "likert",
    text: "即使朋友没及时回复消息，我也能安心做自己的事。",
  },
  {
    id: "q13",
    index: 13,
    dim: "attachment",
    kind: "likert",
    reverse: true,
    text: "我经常担心自己在意的人有一天会渐渐疏远我。",
  },
  {
    id: "q14",
    index: 14,
    dim: "defense",
    kind: "likert",
    text: "跟朋友在一起时，我能自然地聊起自己最近的烦恼。",
  },
  {
    id: "q15",
    index: 15,
    dim: "defense",
    kind: "likert",
    reverse: true,
    text: "遇到困难时，我习惯自己消化，不太愿意让别人看出来。",
  },
  {
    id: "q16",
    index: 16,
    dim: "action",
    kind: "likert",
    text: "我习惯把大目标拆成今天就能动手的小步骤。",
  },
  {
    id: "q17",
    index: 17,
    dim: "action",
    kind: "likert",
    reverse: true,
    text: "面对一个新任务，我常常想来想去还是迈不出第一步。",
  },
  {
    id: "q18",
    index: 18,
    dim: "action",
    kind: "likert",
    text: "我更喜欢先做起来再调整，而不是计划到完美才开始。",
  },
  {
    id: "q19",
    index: 19,
    dim: "processing",
    kind: "likert",
    text: "我更相信亲身经历和实际数据，而不是理论推演。",
  },
  {
    id: "q20",
    index: 20,
    dim: "processing",
    kind: "likert",
    reverse: true,
    text: "我常常被各种新奇的创意和脑洞吸引，觉得比具体事务有意思多了。",
  },
  {
    id: "q21",
    index: 21,
    dim: "processing",
    kind: "likert",
    text: "做事时我喜欢有清晰的流程和步骤可循。",
  },
  {
    id: "q22",
    index: 22,
    dim: "decision",
    kind: "likert",
    text: "讨论问题时，我更关注事情本身的对错而非个人感受。",
  },
  {
    id: "q23",
    index: 23,
    dim: "decision",
    kind: "likert",
    reverse: true,
    text: "做决策时，我首先考虑的是相关人的感受。",
  },
  {
    id: "q24",
    index: 24,
    dim: "decision",
    kind: "likert",
    reverse: true,
    text: "当规则和人情冲突时，我更倾向于照顾人情。",
  },
];
